baseURL = 'https://copettiae.github.io/collection/'
languageCode = 'en-us'
title = 'Collection'
theme = "musica"
[pagination]
  pagerSize = 400
[taxonomies]
  artist = 'Artist'
  country = 'Country'
  decade = 'Decade'
  genre = 'Genre'
  media = 'Media'
  related = 'Related'
  year = 'Year'
