baseURL = 'https://copettiae.github.io/collection/'
languageCode = 'en-us'
title = 'Collection'
theme = "musica"
[pagination]
  pagerSize = 400
[taxonomies]
  artist = 'artist'
  letter = 'letter'
  country = 'country'
  genre = 'genre'
  year = 'year'
  media = 'media'
  decade = 'decade'
  related = 'related'
